spring:
  application:
    name: test-demo
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes: []

server:
  port: 8084
  context-path: /
  error:
    whitelabel:
      enabled: false
    path: /error
  resources:
    add-mappings: false

logging:
  level:
    io.github.resilience4j: DEBUG
    com.example.resilience4jdemo: DEBUG

# 暴露Actuator端点，用于监控
management:
  endpoints:
    enabled-by-default: true
    web:
      base-path: /actuator
      exposure:
        include: health, info, metrics, prometheus
      discovery:
        enabled: true
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs

