spring:
  application:
    name: test-demo
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes: []

server:
  port: 8084
  context-path: /
  error:
    whitelabel:
      enabled: false
    path: /error
  resources:
    add-mappings: false

logging:
  level:
    io.github.resilience4j: DEBUG
    com.example.resilience4jdemo: DEBUG

