spring:
  config:
    import:
      - database.yml
      - resilience4j.yml
      - api.yml
  application:
    name: test-demo
  main:
    allow-bean-definition-overriding: true

server:
  port: 8080 # 监听端口
  context-path: / # 访问路径

# 暴露Actuator端点，用于监控
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus, circuitbreakers, ratelimiters, bulkheads, retries
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    io.github.resilience4j: DEBUG
    com.example.resilience4jdemo: DEBUG

