spring:
  config:
    import:
      - database.yml
  application:
    name: rocketmq-demo
  main:
    allow-bean-definition-overriding: true

server:
  port: 8080 # 监听端口
  context-path: / # 访问路径

common:
  apiHost: http://123.125.111.126

#封装okhttpclient扫描路径
components:
  api:
    base-packages: "com.commons.api.**"

