spring:
  config:
    import:
      - database.yml
      - resilience4j.yml
      - api.yml
      - security.yml
      - actuator.yml
  application:
    name: test-demo
  main:
    allow-bean-definition-overriding: true

server:
  port: 8085 # 监听端口
  context-path: / # 访问路径

logging:
  level:
    io.github.resilience4j: DEBUG
    com.example.resilience4jdemo: DEBUG

