spring:
  redis:
    master:
      host: 127.0.0.1
      port: 6379
      password: 123456
      database: 0
      timeout: 3000ms
    slaves:
      - host: 127.0.0.1
        port: 6380
        password: 123456
        database: 0
        timeout: 3000ms
      - host: 127.0.0.1
        port: 6381
        password: 123456
        database: 0
        timeout: 3000ms
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5
        max-wait: 3000ms